<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="chassis_length" value="0.160"/>
    <xacro:property name="chassis_width" value="0.160"/>
    <xacro:property name="chassis_height" value="0.155"/>
    <xacro:property name="chassis_mass" value="1.5"/>
    <xacro:property name='wheel_diameter' value='0.068'/>
    <xacro:property name="wheel_thickness" value="0.027"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.0"/>
    <xacro:property name="wheel_offset_y" value="0.105"/>
    <xacro:property name="wheel_offset_z" value="-0.031"/>
    <xacro:property name="caster_wheel_diameter" value="0.038"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="-0.1146"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_diameter/2 + caster_wheel_diameter/2}"/>
</robot>