pseye_video_source:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 60.0
      io_method: "mmap"
      frame_id: "camera_link_optical"
      pixel_format: "yuyv2rgb"  # see ros2 run usb_cam usb_cam_node_exe --ros-args -p pixel_format:="test" for list of supported formats
      # av_device_format: "YUV422P"
      image_width: 640
      image_height: 480
      camera_name: "pseye"
      camera_info_url: "package://penelobot/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
