# Based on the X2 model
ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 
    # /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 115200
    lidar_type: 1
    device_type: 0
    sample_rate: 3
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: true
    inverted: false
    auto_reconnect: true
    isSingleChannel: true
    intensity_bit: 0
    intensity: false
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 12.0
    range_min: 0.1
    frequency: 12.0
    invalid_range_is_inf: false
    debug: false
    force_standard_angle: true
    discard_seam_points: 29

